jobs:

  - name: testing-something-chimp
    type: runSh
    steps:
      - IN: test-repo
        switch: off
      - IN: test_shippable_runCI
      - TASK:
        - script: cd ./IN/test-repo/gitRepo/
        - script: sh setup.sh
        - script: npm install
        - script: xvfb-run --server-args="-screen 0, 1920x1080x24" npm test

  - name: testing-something-watir-browserstack
    type: runSh
    steps:
      - IN: test-repo
        switch: off
      - IN: test_shippable_runCI
      - IN: browser-stack-connect
      - TASK:
        - script: cd ./IN/test-repo/gitRepo/
        - script: sh rb_setup.sh
        - script: gem install bundle
        - script: bundle install
        - script: cucumber