jobs:

  # 1. Test
  - name: testing-something
    type: runSh
    steps:
      - IN: test-repo
        switch: off
      - IN: test_shippable_runCI
      - TASK:
        - script: cd ./IN/test-repo/gitRepo/
        - script: sh setup.sh
        - script: npm install
        - script: xvfb-run --server-args="-screen 0, 1920x1080x24" npm test
