jobs:

  # 1. Test
  - name: testing-something
    type: runSh
    steps:
      - IN: test-repo
        switch: off
      - IN: test_shippable_runCI
      - TASK:
        - script: echo $BUILD_ID
        - script: echo $BUILD_NUMBER
        - script: export URL=homes-site.test.bxm.net.au
        - script: cd ./IN/test-repo/gitRepo/
        - script: npm install
        - script: npm test
